# 应用服务 WEB 访问端口
server.port: 8091

spring:
  application.name: ai-deepseek
  profiles:
    active: dev
  ai:
    deepseek:
      api-key: ${DEEPSEEK-API-KEY}
      chat:
        options:
          model: deepseek-chat
          # 温度
          temperature: 0.0
          # 最大token数
#          max-tokens: 8192

      baseUrl: https://api.deepseek.com