# 应用服务 WEB 访问端口
server.port: 8082

spring:
  application.name: ai-openai
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${DEEPSEEK-API-KEY}
      # DeepSeek 的 API 地址
      base-url: https://api.deepseek.com
      embedding:
        # 禁用 OpenAI 的嵌入模块，DeepSeek 的 API 暂不支持此功能
        enabled: false
      chat:
        options:
          # 控制输出随机性
          #temperature: 1.3
          model: deepseek-v4-flash  # 指定 DeepSeek 的模型
